# Generated by Django 5.0.7 on 2024-07-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infoutil', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='description',
        ),
    ]
