# Generated by Django 5.0.7 on 2024-07-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoutil', '0003_rename_content_post_description'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='infoutil',
            name='description2',
            field=models.CharField(default='no disponible', max_length=200, verbose_name='Descripción2'),
        ),
        migrations.AlterField(
            model_name='infoutil',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
    ]
