# Generated by Django 5.0.7 on 2024-07-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoutil', '0004_delete_post_infoutil_description2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoutil',
            name='description2',
            field=models.CharField(default='no disponible', max_length=500, verbose_name='Descripción2'),
        ),
    ]
