# Generated by Django 5.0.7 on 2024-07-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoutil', '0006_alter_infoutil_description2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoutil',
            name='description',
            field=models.TextField(verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='infoutil',
            name='description2',
            field=models.TextField(default='no disponible', verbose_name='Descripción2'),
        ),
    ]
